name: base
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - ca-certificates=2022.10.11=haa95532_0
  - certifi=2022.12.7=py39haa95532_0
  - cffi=1.15.1=py39h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.5=py39haa95532_0
  - conda=22.11.1=py39haa95532_4
  - conda-content-trust=0.1.3=py39haa95532_0
  - conda-package-handling=1.9.0=py39h8cc25b3_1
  - console_shortcut_miniconda=0.1.1=haa95532_0
  - cryptography=38.0.1=py39h21b164f_0
  - eigen=3.3.7=h59b6b97_1
  - glib=2.69.1=h5dc1a3c_2
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - hdf5=1.12.1=h1756f20_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py39haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - jpeg=9e=h2bbff1b_0
  - lerc=3.0=hd77b12b_0
  - libclang=12.0.0=default_h627e005_2
  - libdeflate=1.8=h2bbff1b_5
  - libffi=3.4.2=hd77b12b_6
  - libiconv=1.16=h2bbff1b_2
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.20.1=h23ce68f_0
  - libtiff=4.5.0=h8a3f274_0
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.2.4=h2bbff1b_0
  - libwebp-base=1.2.4=h2bbff1b_0
  - libxml2=2.9.14=h0ad7f3c_0
  - libxslt=1.1.35=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - menuinst=1.4.19=py39h59b6b97_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.1=py39h277e83a_0
  - mkl_random=1.2.2=py39hf11a4ad_0
  - opencv=4.6.0=py39h104de81_2
  - openssl=1.1.1s=h2bbff1b_0
  - pcre=8.45=hd77b12b_0
  - pip=22.3.1=py39haa95532_0
  - pluggy=1.0.0=py39haa95532_1
  - powershell_shortcut_miniconda=0.0.1=haa95532_0
  - pycosat=0.6.4=py39h2bbff1b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.15=h6244533_2
  - qt-main=5.15.2=he8e5bd7_7
  - qt-webengine=5.15.9=hb9a9bb5_4
  - qtwebkit=5.212=h3ad3cdb_4
  - requests=2.28.1=py39haa95532_0
  - ruamel.yaml=0.17.21=py39h2bbff1b_0
  - ruamel.yaml.clib=0.2.6=py39h2bbff1b_1
  - setuptools=65.5.0=py39haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.0=h2bbff1b_0
  - toolz=0.12.0=py39haa95532_0
  - tqdm=4.64.1=py39haa95532_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.13=py39haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - wincertstore=0.2=py39haa95532_2
  - xz=5.2.8=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.2=h19a0ad4_0
  - pip:
      - aiohttp==3.8.3
      - aiosignal==1.3.1
      - albumentations==1.3.0
      - appdirs==1.4.4
      - async-timeout==4.0.2
      - attrs==22.2.0
      - click==8.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - docker-pycreds==0.4.0
      - fonttools==4.38.0
      - frozenlist==1.3.3
      - fsspec==2022.11.0
      - gitdb==4.0.10
      - gitpython==3.1.30
      - imagecodecs==2022.12.24
      - imageio==2.24.0
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - lightning-utilities==0.5.0
      - matplotlib==3.6.3
      - multidict==6.0.4
      - networkx==3.0
      - numpy==1.24.1
      - opencv-python-headless==4.7.0.68
      - packaging==23.0
      - pandas==1.5.2
      - pathtools==0.1.2
      - pillow==9.4.0
      - protobuf==3.20.1
      - psutil==5.9.4
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytorch-lightning==1.8.6
      - pytz==2022.7.1
      - pywavelets==1.4.1
      - pyyaml==6.0
      - qudida==0.0.4
      - scikit-image==0.19.3
      - scikit-learn==1.2.0
      - scipy==1.10.0
      - sentry-sdk==1.13.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - tensorboardx==2.5.1
      - threadpoolctl==3.1.0
      - tifffile==2022.10.10
      - torch==1.13.1
      - torchmetrics==0.11.0
      - torchvision==0.14.1
      - typing-extensions==4.4.0
      - wandb==0.13.9
      - yarl==1.8.2
prefix: C:\Users\echen\miniconda3
